<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CategoryService.Core\CategoryService.Core.csproj" />
      <ProjectReference Include="..\CategoryService.Infrastructure\CategoryService.Infrastructure.csproj" />
      <ProjectReference Include="..\CategoryService.Shared\CategoryService.Shared.csproj" />
    </ItemGroup>

</Project>
